Repository Cratis/ApplicationModel, pull requests merged in 2024-08, with the labels that each got.

#69 Downgrading mongo to avoid problems upstream
  Directory.Packages.props
Labels: patch

#70 Seting MongoDB to be version 2.25.0
  Directory.Packages.props
Labels: patch

#72 Fixing so that the route templates are correct for arguments
  Samples/eCommerce/Basic/Web/API/Products/SetStockForProduct.ts
  Samples/eCommerce/Basic/Web/API/Users/ChangeProfilePicture.ts
  Source/DotNET/Tools/ProxyGenerator/CommandExtensions.cs
  Source/DotNET/Tools/ProxyGenerator/MethodInfoExtensions.cs
  Source/DotNET/Tools/ProxyGenerator/QueryExtensions.cs
  Source/DotNET/Tools/ProxyGenerator/Templates/Command.hbs
  Source/DotNET/Tools/ProxyGenerator/Templates/CommandDescriptor.cs
  Source/DotNET/Tools/ProxyGenerator/Templates/ObservableQuery.hbs
  Source/DotNET/Tools/ProxyGenerator/Templates/Query.hbs
  Source/DotNET/Tools/ProxyGenerator/Templates/QueryDescriptor.cs
Labels: patch

#74 Adding & when microservice argument is present
  Source/JavaScript/Applications/queries/ObservableQueryConnection.ts
Labels: patch

#78 Changing how we do the Microsoft Identity Platform auth
  Samples/eCommerce/Basic/Main/Program.cs
  Source/DotNET/Applications/Identity/MicrosoftIDentityPlatformAuthHandler.cs
  Source/DotNET/Applications/Identity/MicrosoftIdentityPlatformIdentityApplicationBuilderExtensions.cs
  Source/DotNET/Applications/Identity/MicrosoftIdentityPlatformIdentityResolverMiddleware.cs
  Source/DotNET/Applications/Identity/MicrosoftIdentityPlatformIdentityServiceCollectionExtensions.cs
Labels: major

#79 Fixing so that we are using the same ClientPrincipal type as defined by Microsoft
  Source/DotNET/Applications.Specs/Identity/for_IdentityProviderEndpoint/given/a_valid_identity_request.cs
  Source/DotNET/Applications.Specs/Identity/for_IdentityProviderEndpoint/when_handling/and_claims_are_missing.cs
  Source/DotNET/Applications.Specs/Identity/for_IdentityProviderEndpoint/when_handling/and_identity_is_valid_with_multiple_roles.cs
  Source/DotNET/Applications/Identity/ClientPrincipal.cs
  Source/DotNET/Applications/Identity/IdentityProviderEndpoint.cs
  Source/DotNET/Applications/Identity/MicrosoftIDentityPlatformAuthHandler.cs
  Source/DotNET/Applications/Identity/MicrosoftIdentityPlatformRequestExtensions.cs
  Source/DotNET/Applications/Identity/RequestExtensions.cs
Labels: patch

#80 Fix/observable return types
  ApplicationModel.sln
  Source/DotNET/Tools/ProxyGenerator/Templates/ObservableQuery.hbs
Labels: patch

#81 Disable sort-imports ESLint rule for proxies
  Source/DotNET/Tools/ProxyGenerator/Templates/Command.hbs
  Source/DotNET/Tools/ProxyGenerator/Templates/Interface.hbs
  Source/DotNET/Tools/ProxyGenerator/Templates/ObservableQuery.hbs
  Source/DotNET/Tools/ProxyGenerator/Templates/Query.hbs
  Source/DotNET/Tools/ProxyGenerator/Templates/Type.hbs
  Source/DotNET/Tools/ProxyGenerator/Templates/index.hbs
Labels: patch

#82 Removing validator + disabling no-empty-interface rule
  Source/DotNET/Tools/ProxyGenerator/Templates/Command.hbs
Labels: patch

#83 this should be present
  Source/DotNET/Tools/ProxyGenerator/Templates/Command.hbs
Labels: patch

#85 Adding a [Roles] attribute for specifying roles in a more meaningful way
  Source/DotNET/Applications/Authorization/RolesAttribute.cs
Labels: minor

#86 Adding AttributeUsage
  Source/DotNET/Applications/Authorization/RolesAttribute.cs
Labels: patch

#77 Feature: Serializing Dates and time MongoDb
  Source/DotNET/MongoDB/ConceptSerializer.cs
Labels: patch

#155 Adding on* methods for command result
  Directory.Packages.props
  Source/JavaScript/Applications.React.MVVM/package.json
  Source/JavaScript/Applications.React/package.json
  Source/JavaScript/Applications.Vite/package.json
  Source/JavaScript/Applications/commands/CommandResult.ts
  Source/JavaScript/Applications/commands/for_CommandResult/when_chaining_callbacks/and_result_has_exceptions.ts
  Source/JavaScript/Applications/commands/for_CommandResult/when_chaining_callbacks/and_result_is_invalid.ts
  Source/JavaScript/Applications/commands/for_CommandResult/when_chaining_callbacks/and_result_is_successful.ts
  Source/JavaScript/Applications/commands/for_CommandResult/when_chaining_callbacks/and_result_is_unauthorized.ts
Labels: minor

#162 Feature/missing-mvvm-features
  Samples/eCommerce/Basic/Web/App.tsx
  Samples/eCommerce/Basic/Web/Feature.tsx
  Samples/eCommerce/Basic/Web/FeatureViewModel.ts
  Samples/eCommerce/Basic/Web/StandardDialog.tsx
  Source/JavaScript/Applications.React.MVVM/dialogs/DialogButtons.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/DialogMediator.tsx
  Source/JavaScript/Applications.React.MVVM/dialogs/DialogMediatorHandler.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/DialogRegistration.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/Dialogs.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/IDialogMediatorHandler.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/IDialogs.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/StandardDialogRequest.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/StandardDialogs.tsx
  Source/JavaScript/Applications.React.MVVM/dialogs/index.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/useDialogRequest.tsx
  Source/JavaScript/Applications.React.MVVM/index.ts
  Source/JavaScript/Applications.React.MVVM/messaging/IMessenger.ts
  Source/JavaScript/Applications.React.MVVM/messaging/Message.ts
  Source/JavaScript/Applications.React.MVVM/messaging/Messenger.ts
  Source/JavaScript/Applications.React.MVVM/messaging/index.ts
  Source/JavaScript/Applications.React.MVVM/package.json
  Source/JavaScript/Applications.React.MVVM/withViewModel.tsx
  Source/JavaScript/Applications.React/dialogs/DialogResult.ts
Labels: minor

#163 Fix messenger to actually work - added tests to verify
  Source/JavaScript/Applications.React.MVVM/for_RemoveMeSpec/when_actual_spec_added.ts
  Source/JavaScript/Applications.React.MVVM/messaging/Messenger.ts
  Source/JavaScript/Applications.React.MVVM/messaging/for_Messenger/when_publishing_message_with_subscriber.ts
Labels: patch
