Repository Cratis/ApplicationModel, pull requests merged in 2024-10, with the labels that each got.

#272 set explicit package version 8.0.4
  Directory.Build.props
  Directory.Packages.props
Labels: patch

#287 Extension method for using a specific identity provider
  .github/workflows/dotnet-build.yml
  .github/workflows/publish.yml
  .github/workflows/pull-requests.yml
  Source/DotNET/Applications/Identity/IdentityProviderServiceCollectionExtensions.cs
Labels: minor

#293 Feature/dialogs
  Documentation/frontend/react.mvvm/dialogs.md
  Samples/eCommerce/Basic/Web/App.tsx
  Samples/eCommerce/Basic/Web/BusyIndicatorDialog.tsx
  Samples/eCommerce/Basic/Web/ConfirmationDialog.tsx
  Samples/eCommerce/Basic/Web/Feature.tsx
  Samples/eCommerce/Basic/Web/FeatureViewModel.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/BusyIndicator.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/BusyIndicatorDialogRequest.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/ConfirmationDialogs.tsx
  Source/JavaScript/Applications.React.MVVM/dialogs/DialogComponents.tsx
  Source/JavaScript/Applications.React.MVVM/dialogs/DialogMediatorHandler.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/DialogRegistration.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/Dialogs.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/IDialogMediatorHandler.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/IDialogs.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/index.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/useDialogRequest.tsx
  Source/JavaScript/Applications.React/package.json
Labels: major

#302 Adding support for detached method on ViewModels
  Samples/eCommerce/Basic/Web/App.tsx
  Samples/eCommerce/Basic/Web/Feature.tsx
  Samples/eCommerce/Basic/Web/FeatureViewModel.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/IViewModelDetached.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/index.ts
  Source/JavaScript/Applications.React.MVVM/withViewModel.tsx
  Source/JavaScript/Applications/queries/ObservableQueryConnection.ts
  Source/JavaScript/Applications/queries/ObservableQueryFor.ts
Labels: minor

#304 Avoiding problems if multiple calls to unsubscribe
  Source/JavaScript/Applications/queries/ObservableQuerySubscription.ts
Labels: patch

#308 Making sure we initialize and dispose correct instances - working around StrictMode multi initialization
  Samples/eCommerce/Basic/Web/FeatureViewModel.ts
  Source/JavaScript/Applications.React.MVVM/withViewModel.tsx
  Source/JavaScript/Applications/queries/ObservableQueryConnection.ts
Labels: patch

#309 Fixing export mistake for IViewModelDetached
  Samples/eCommerce/Basic/Web/FeatureViewModel.ts
  Source/JavaScript/Applications.React.MVVM/IViewModelDetached.ts
  Source/JavaScript/Applications.React.MVVM/dialogs/index.ts
  Source/JavaScript/Applications.React.MVVM/index.ts
  Source/JavaScript/Applications.React.MVVM/withViewModel.tsx
Labels: patch

#314 Fix/command-serialization
  Source/JavaScript/Applications.React.MVVM/package.json
  Source/JavaScript/Applications.React/package.json
  Source/JavaScript/Applications.Vite/package.json
  Source/JavaScript/Applications/commands/Command.ts
  Source/JavaScript/Applications/package.json
Labels: patch

#317 Fix/disconnect ws
  .vscode/launch.json
  Samples/eCommerce/Basic/Web/Feature.tsx
  Samples/eCommerce/Basic/Web/FeatureViewModel.ts
  Samples/eCommerce/Basic/Web/vite.config.mts
  Source/DotNET/Applications/Queries/ClientEnumerableObservable.cs
  Source/DotNET/Applications/Queries/ClientObservable.cs
  Source/DotNET/Applications/Queries/ClientObservableLogMessages.cs
  Source/DotNET/Applications/Queries/IWebSocketConnectionHandler.cs
  Source/DotNET/Applications/Queries/QueryActionFilter.cs
  Source/DotNET/Applications/Queries/WebSocketConnectionHandler.cs
  Source/JavaScript/Applications/queries/ObservableQueryConnection.ts
Labels: patch

#318 Fix/cancel
  Samples/eCommerce/Basic/Web/vite.config.mts
  Source/DotNET/MongoDB/MongoCollectionExtensions.cs
  Source/DotNET/MongoDB/MongoCollectionExtensionsLogging.cs
Labels: patch

#323 Feature/query-provider
  Samples/eCommerce/Basic/Web/FeatureViewModel.ts
  Source/JavaScript/Applications.React.MVVM/index.ts
  Source/JavaScript/Applications.React.MVVM/tsconfig.json
  Source/JavaScript/Applications.React/ApplicationModel.tsx
  Source/JavaScript/Applications.React/Bindings.ts
  Source/JavaScript/Applications/queries/IObservableQueryFor.ts
  Source/JavaScript/Applications/queries/IQuery.ts
  Source/JavaScript/Applications/queries/IQueryFor.ts
  Source/JavaScript/Applications/queries/IQueryProvider.ts
  Source/JavaScript/Applications/queries/ObservableQueryFor.ts
  Source/JavaScript/Applications/queries/QueryProvider.ts
  Source/JavaScript/Applications/queries/index.ts
Labels: minor

#325 Adding the possibility to specify identity details provider as options
  Source/DotNET/Applications/ApplicationModelOptions.cs
  Source/DotNET/Applications/HostBuilderExtensions.cs
  Source/DotNET/Applications/Identity/IdentityProviderServiceCollectionExtensions.cs
  Source/DotNET/Applications/Identity/TypeIsNotAnIdentityDetailsProvider.cs
Labels: minor

#332 Fix/disposables
  Source/DotNET/Applications/Queries/ClientObservable.cs
  Source/DotNET/MongoDB/MongoCollectionExtensions.cs
  Source/DotNET/MongoDB/MongoCollectionExtensionsLogging.cs
Labels: patch

#333 Append header to Commands
  Source/JavaScript/Applications/commands/Command.ts
Labels: patch

#334 Only create the viewModel once for a component
  Samples/eCommerce/Basic/Web/Feature.tsx
  Samples/eCommerce/Basic/Web/FeatureViewModel.ts
  Source/JavaScript/Applications.React.MVVM/withViewModel.tsx
Labels: patch

#335 Fix/viewmodel-instantiation
  Samples/eCommerce/Basic/Web/App.tsx
  Samples/eCommerce/Basic/Web/package.json
  Source/JavaScript/Applications.React.MVVM/withViewModel.tsx
  Source/JavaScript/Applications.React/ApplicationModel.tsx
Labels: minor

#342 Introducing onFailed() for CommandResults
  Source/JavaScript/Applications/commands/CommandResult.ts
  Source/JavaScript/Applications/commands/for_CommandResult/when_chaining_callbacks/and_result_has_exceptions.ts
  Source/JavaScript/Applications/commands/for_CommandResult/when_chaining_callbacks/and_result_is_invalid.ts
  Source/JavaScript/Applications/commands/for_CommandResult/when_chaining_callbacks/and_result_is_successful.ts
  Source/JavaScript/Applications/commands/for_CommandResult/when_chaining_callbacks/and_result_is_unauthorized.ts
Labels: minor

#344 update Cratis.Fundamentals
  Directory.Packages.props
  Source/JavaScript/Applications.React.MVVM/package.json
  Source/JavaScript/Applications.React/package.json
  Source/JavaScript/Applications.Vite/package.json
  Source/JavaScript/Applications/package.json
Labels: patch

#352 Feature/well known bindings
  Samples/eCommerce/Basic/Web/App.tsx
  Samples/eCommerce/Basic/Web/TestParams.tsx
  Samples/eCommerce/Basic/Web/TestParamsViewModel.ts
  Samples/eCommerce/Basic/Web/TestQuery.tsx
  Samples/eCommerce/Basic/Web/TestQueryViewModel.ts
  Source/JavaScript/Applications.React.MVVM/Bindings.ts
  Source/JavaScript/Applications.React.MVVM/WellKnownBindings.ts
  Source/JavaScript/Applications.React.MVVM/index.ts
  Source/JavaScript/Applications.React.MVVM/withViewModel.tsx
  Source/JavaScript/Applications.React/Bindings.ts
  Source/JavaScript/Applications.React/WellKnownBindings.ts
  Source/JavaScript/Applications.React/index.ts
Labels: minor

#358 Returning null if type is unknown for the ConceptSerializer
  .globalconfig
  Source/DotNET/Orleans/Concepts/ConceptSerializer.cs
Labels: patch
